### ISSUE TITLE
会支持后端部署不

### ISSUE THREAD

**Issue by wallleap** [wzn556/NotifyMe-Tuorials#1]
后续会支持自己部署吗，类似 Bark-server 那种

**Comment by wzn556** [comment]
目前自建服务端无论是从安全性，还是稳定性来看，都没有明显的优势，因此暂时不会考虑支持。
如果过于担心数据泄露，可以根据软件内的aeskey对消息内容进行加密，配置好对应的数据内容后软件可以自动解密。
