### ISSUE TITLE
三星手机提示频繁崩溃

### ISSUE THREAD

**Issue by Lianjiangwuli** [wzn556/NotifyMe-Tuorials#2]
不知是不是bug，频繁提示崩溃

**Comment by wzn556** [comment]
哪个版本？是如何触发的？

**Comment by Lianjiangwuli** [comment]
> 哪个版本？是如何触发的？

手机系统oneui6.1.1，应用版本3.3.1（15）,在电池设置中提示“该应用频繁崩溃耗电大，建议深度休眠”，但没出现闪退之类影响使用的情况

**Comment by wzn556** [comment]
> > 哪个版本？是如何触发的？
> 
> 手机系统oneui6.1.1，应用版本3.3.1（15）,在电池设置中提示“该应用频繁崩溃耗电大，建议深度休眠”，但没出现闪退之类影响使用的情况

提供一下JSON和FCM诊断工具内的截图
